(function(){
const DAYS=['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado','Domingo'];
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));

function addStyles(){if(document.getElementById('profAdmStyle'))return;const s=document.createElement('style');s.id='profAdmStyle';s.textContent=`
#tab-profissionais .prof-adm-head{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:22px}
#tab-profissionais .prof-adm-head h2,#tab-profissionais .prof-adm-form-head h3{margin:5px 0;color:var(--azul,#003070)}
#tab-profissionais .prof-adm-head p{margin:0;color:#68727d}
#tab-profissionais .prof-adm-list{display:grid;gap:12px}
#tab-profissionais .prof-adm-card{display:flex;align-items:center;gap:16px;background:#fff;border:1px solid #e4e9ed;border-radius:18px;padding:14px;box-shadow:0 6px 20px rgba(27,58,107,.06)}
#tab-profissionais .prof-adm-avatar{width:64px;height:64px;border-radius:15px;overflow:hidden;background:#f1f4f5;display:grid;place-items:center;flex:none}
#tab-profissionais .prof-adm-avatar img{width:100%;height:100%;object-fit:cover}
#tab-profissionais .prof-adm-info{display:flex;flex-direction:column;gap:4px;flex:1;min-width:0}
#tab-profissionais .prof-adm-info strong{color:var(--azul,#003070);font-size:.98rem}
#tab-profissionais .prof-adm-info span{color:var(--verde,#1B5E3F);font-size:.82rem}
#tab-profissionais .prof-adm-info small{color:#7b858d}
#tab-profissionais .prof-adm-actions{display:flex;gap:8px;flex-wrap:wrap}
#tab-profissionais .prof-adm-actions button,#tab-profissionais .ghost-btn{border:1px solid #dce3e7;background:#fff;color:var(--azul,#003070);border-radius:10px;padding:9px 12px;cursor:pointer;font-weight:700}
#tab-profissionais .prof-adm-actions .danger{color:#b42318}
#tab-profissionais .prof-adm-form{background:#fff;border:1px solid #e3e9ed;border-radius:20px;padding:22px;margin-bottom:20px;box-shadow:0 10px 30px rgba(27,58,107,.06)}
#tab-profissionais .prof-adm-form-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}
#tab-profissionais .prof-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}
#tab-profissionais .prof-form-grid label{display:flex;flex-direction:column;gap:6px;font-size:.8rem;font-weight:700;color:#3e4a54}
#tab-profissionais .prof-form-grid .full{grid-column:1/-1}
#tab-profissionais .prof-form-grid input,#tab-profissionais .prof-form-grid textarea{font:inherit;font-weight:400;border:1px solid #dce3e7;border-radius:11px;padding:10px;background:#fff;box-sizing:border-box;width:100%}
#tab-profissionais .prof-form-grid textarea{resize:vertical}
#tab-profissionais .prof-form-grid small{font-weight:400;color:#7b858d}
#tab-profissionais .prof-form-grid .check{justify-content:center;flex-direction:row;align-items:center}
#tab-profissionais .prof-hours-edit{margin-top:22px;border-top:1px solid #edf0f2;padding-top:18px}
#tab-profissionais .prof-hours-edit h4{margin:0 0 12px;color:var(--azul,#003070)}
#tab-profissionais .hour-row{display:grid;grid-template-columns:1.5fr 1fr auto 1fr;gap:10px;align-items:center;padding:7px 0;font-size:.82rem}
#tab-profissionais .hour-row label{font-weight:600}
#tab-profissionais .hour-row input[type=time]{border:1px solid #dce3e7;border-radius:9px;padding:7px;min-width:0}
#tab-profissionais .prof-form-actions{display:flex;gap:10px;margin-top:20px;flex-wrap:wrap}
#tab-profissionais .prof-empty{padding:34px;text-align:center;color:#68727d;background:#fff;border:1px dashed #d9e0e4;border-radius:16px}
@media(max-width:700px){#tab-profissionais .prof-adm-head{align-items:flex-start;flex-direction:column}#tab-profissionais .prof-adm-card{align-items:flex-start;flex-wrap:wrap}#tab-profissionais .prof-adm-actions{width:100%}#tab-profissionais .prof-form-grid{grid-template-columns:1fr}#tab-profissionais .prof-form-grid .full{grid-column:auto}#tab-profissionais .hour-row{grid-template-columns:1fr 1fr 1fr}#tab-profissionais .hour-row label{grid-column:1/-1}}
`;document.head.appendChild(s);}

function ensureTab(){let tab=document.getElementById('tab-profissionais');if(!tab){tab=document.createElement('section');tab.id='tab-profissionais';tab.className='tab-content';tab.style.display='none';const config=document.getElementById('tab-config');if(config&&config.parentNode)config.parentNode.insertBefore(tab,config);else{const app=document.querySelector('main')||document.body;app.appendChild(tab);}}
let link=document.getElementById('nav-profissionais');if(!link){const nav=document.querySelector('aside nav,.sidebar nav,.sidebar,.admin-sidebar,nav');if(nav){link=document.createElement('button');link.id='nav-profissionais';link.type='button';link.className='nav-item';link.innerHTML='👨‍⚕️ <span>Profissionais</span>';link.addEventListener('click',openTab);nav.appendChild(link);}}
return tab;}
function openTab(){document.querySelectorAll('.tab-content').forEach(x=>x.style.display='none');const tab=document.getElementById('tab-profissionais');if(tab)tab.style.display='block';document.querySelectorAll('#nav-profissionais').forEach(x=>x.classList.add('active'));const title=document.querySelector('.topbar-title,#pageTitle,.page-title,h1');if(title&&title.dataset.profOriginal===undefined){title.dataset.profOriginal=title.textContent;title.textContent='Profissionais';}}

async function load(){const {data,error}=await sb.from('profissionais').select('*').order('ordem').order('nome');const el=document.getElementById('profLista');if(!el)return;if(error){el.innerHTML='<div class="prof-empty">Erro ao carregar profissionais: '+esc(error.message)+'</div>';return;}el.innerHTML=(data||[]).map(p=>`<div class="prof-adm-card"><div class="prof-adm-avatar">${p.foto_url?`<img src="${esc(p.foto_url)}" alt="">`:'<span>👤</span>'}</div><div class="prof-adm-info"><strong>${esc(p.nome)}</strong><span>${esc(p.cargo||p.area_atuacao||'')}</span><small>${p.ativo?'Publicado no site':'Oculto no site'}</small></div><div class="prof-adm-actions"><button type="button" onclick='window.editarProfissional(${JSON.stringify(p.id)})'>Editar</button><button type="button" class="danger" onclick='window.excluirProfissional(${JSON.stringify(p.id)})'>Excluir</button></div></div>`).join('')||'<div class="prof-empty">Nenhum profissional cadastrado.</div>';}
function form(p={}){const f=document.getElementById('profForm');f.style.display='block';f.innerHTML=`<div class="prof-adm-form-head"><div><span class="tag">Perfil profissional</span><h3>${p.id?'Editar profissional':'Novo profissional'}</h3></div><button type="button" class="ghost-btn" onclick="document.getElementById('profForm').style.display='none'">Fechar</button></div><form id="profissionalForm"><input type="hidden" id="pfId" value="${esc(p.id||'')}"><div class="prof-form-grid"><label>Nome<input id="pfNome" required value="${esc(p.nome||'')}"></label><label>Cargo / função<input id="pfCargo" value="${esc(p.cargo||'')}"></label><label>Área de actuação<input id="pfArea" value="${esc(p.area_atuacao||'')}"></label><label>Ordem<input id="pfOrdem" type="number" value="${Number(p.ordem||0)}"></label><label class="full">Pequena biografia<textarea id="pfBio" rows="3">${esc(p.biografia||'')}</textarea></label><label class="full">O que faz / explicação para o paciente<textarea id="pfDesc" rows="4">${esc(p.descricao||'')}</textarea></label><label>Foto<input id="pfFoto" type="file" accept="image/*"><small>JPG, PNG ou WebP.</small></label><label class="check"><input id="pfAtivo" type="checkbox" ${p.ativo!==false?'checked':''}> Mostrar este profissional no site</label></div><div class="prof-hours-edit"><h4>Horários de atendimento</h4>${DAYS.map(d=>{const x=(p.horarios||[]).find(a=>a.dia===d)||{};return `<div class="hour-row"><label><input class="pf-day" data-day="${d}" type="checkbox" ${x.inicio?'checked':''}> ${d}</label><input class="pf-start" data-day="${d}" type="time" value="${esc(x.inicio||'')}"><span>até</span><input class="pf-end" data-day="${d}" type="time" value="${esc(x.fim||'')}"></div>`;}).join('')}</div><div class="prof-form-actions"><button class="btn-p" type="submit">Guardar profissional</button><button type="button" class="ghost-btn" onclick="document.getElementById('profForm').style.display='none'">Cancelar</button></div></form>`;document.getElementById('profissionalForm').onsubmit=save;f.scrollIntoView({behavior:'smooth',block:'start'});}
async function save(e){e.preventDefault();const id=document.getElementById('pfId').value;let foto=null;const file=document.getElementById('pfFoto').files[0];if(file){const path='profissionais/'+crypto.randomUUID()+'.'+(file.name.split('.').pop()||'jpg');const up=await sb.storage.from('profissionais').upload(path,file,{upsert:false,contentType:file.type});if(up.error){showToast('Erro ao enviar foto: '+up.error.message,'err');return;}foto=sb.storage.from('profissionais').getPublicUrl(path).data.publicUrl;}const horarios=DAYS.map(d=>{const c=document.querySelector(`.pf-day[data-day="${CSS.escape(d)}"]`),a=document.querySelector(`.pf-start[data-day="${CSS.escape(d)}"]`),b=document.querySelector(`.pf-end[data-day="${CSS.escape(d)}"]`);return {dia:d,inicio:a.value,fim:b.value,disponivel:c.checked};}).filter(x=>x.disponivel&&x.inicio&&x.fim);const obj={nome:document.getElementById('pfNome').value.trim(),cargo:document.getElementById('pfCargo').value.trim(),area_atuacao:document.getElementById('pfArea').value.trim(),biografia:document.getElementById('pfBio').value.trim(),descricao:document.getElementById('pfDesc').value.trim(),ordem:Number(document.getElementById('pfOrdem').value||0),ativo:document.getElementById('pfAtivo').checked,horarios};if(foto)obj.foto_url=foto;const {error}=id?await sb.from('profissionais').update(obj).eq('id',id):await sb.from('profissionais').insert(obj);if(error){showToast('Erro ao guardar: '+error.message,'err');return;}showToast('Profissional guardado com sucesso!','ok');document.getElementById('profForm').style.display='none';load();}
window.editarProfissional=async id=>{const {data,error}=await sb.from('profissionais').select('*').eq('id',id).single();if(error)showToast(error.message,'err');else form(data);};
window.excluirProfissional=async id=>{if(!confirm('Excluir este perfil?'))return;const {error}=await sb.from('profissionais').delete().eq('id',id);if(error)showToast('Erro: '+error.message,'err');else{showToast('Profissional removido.','ok');load();}};
function inject(){addStyles();const tab=ensureTab();tab.innerHTML=`<div class="prof-adm-head"><div><span class="tag">Equipa</span><h2>Profissionais</h2><p>Crie e edite os perfis apresentados no site.</p></div><button class="btn-p" id="profNovo" type="button">+ Novo profissional</button></div><div id="profLista" class="prof-adm-list"></div><div id="profForm" class="prof-adm-form" style="display:none"></div>`;document.getElementById('profNovo').onclick=()=>form();load();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject,{once:true});else inject();
})();
