(function(){
const DAYS=['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado','Domingo'];
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function addStyles(){if(document.getElementById('profAdmStyles'))return;const s=document.createElement('style');s.id='profAdmStyles';s.textContent=`
#profAdmRoot{margin:28px 0;font-family:inherit;color:#263442}#profAdmRoot *{box-sizing:border-box}
#profAdmRoot .prof-adm-head{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:24px 26px;margin-bottom:18px;background:linear-gradient(135deg,#fff 0%,#f5f9fb 100%);border:1px solid rgba(0,48,112,.10);border-radius:22px;box-shadow:0 10px 28px rgba(0,48,112,.07)}
#profAdmRoot .prof-adm-head h2{margin:6px 0 5px;color:#003070;font-size:1.45rem}#profAdmRoot .prof-adm-head p{margin:0;color:#697681;font-size:.88rem}.prof-adm-head .tag{display:inline-flex;padding:6px 10px;border-radius:999px;background:rgba(27,94,63,.10);color:#1B5E3F;font-size:.72rem;font-weight:800;text-transform:uppercase;letter-spacing:.06em}
#profAdmRoot .prof-adm-list{display:grid;gap:12px}.prof-adm-card{display:flex;align-items:center;gap:16px;background:#fff;border:1px solid #e2e9ed;border-radius:18px;padding:14px 16px;box-shadow:0 6px 20px rgba(0,48,112,.05);transition:.2s}.prof-adm-card:hover{transform:translateY(-2px);box-shadow:0 10px 28px rgba(0,48,112,.09)}
.prof-adm-avatar{width:68px;height:68px;min-width:68px;border-radius:16px;overflow:hidden;background:#eef4f6;display:grid;place-items:center;color:#003070;font-size:1.5rem}.prof-adm-avatar img{width:100%;height:100%;object-fit:cover}.prof-adm-info{min-width:0;flex:1;display:flex;flex-direction:column;gap:4px}.prof-adm-info strong{color:#003070;font-size:.98rem}.prof-adm-info span{color:#1B5E3F;font-size:.82rem;font-weight:700}.prof-adm-info small{color:#7b8790;font-size:.74rem}.prof-adm-actions{display:flex;gap:8px;flex-wrap:wrap}.prof-adm-actions button,.ghost-btn{border:1px solid #d8e1e6;background:#fff;color:#003070;border-radius:11px;padding:9px 13px;font:inherit;font-size:.78rem;font-weight:800;cursor:pointer;transition:.2s}.prof-adm-actions button:hover,.ghost-btn:hover{background:#f2f7f9}.prof-adm-actions .danger{color:#b42318;border-color:#f0d3d0}.prof-adm-actions .danger:hover{background:#fff5f4}
.prof-adm-form{background:#fff;border:1px solid rgba(0,48,112,.11);border-radius:22px;padding:24px;margin-top:18px;box-shadow:0 12px 34px rgba(0,48,112,.08)}.prof-adm-form-head{display:flex;align-items:center;justify-content:space-between;gap:15px;padding-bottom:17px;margin-bottom:20px;border-bottom:1px solid #edf1f3}.prof-adm-form-head h3{margin:5px 0 0;color:#003070;font-size:1.15rem}.prof-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.prof-form-grid label{display:flex;flex-direction:column;gap:7px;color:#40505c;font-size:.78rem;font-weight:800}.prof-form-grid .full{grid-column:1/-1}.prof-form-grid input,.prof-form-grid textarea{width:100%;border:1px solid #d9e2e7;border-radius:12px;background:#fff;color:#273642;padding:11px 12px;font:inherit;font-size:.86rem;font-weight:400;outline:none;transition:.2s}.prof-form-grid input:focus,.prof-form-grid textarea:focus{border-color:#1B5E3F;box-shadow:0 0 0 3px rgba(27,94,63,.09)}.prof-form-grid textarea{resize:vertical;line-height:1.55}.prof-form-grid input[type=file]{padding:9px;background:#f8fafb}.prof-form-grid small{font-weight:400;color:#7a858d}.prof-form-grid .check{flex-direction:row;align-items:center;justify-content:flex-start;gap:9px;padding-top:27px}.prof-form-grid .check input{width:auto;accent-color:#1B5E3F}
.prof-hours-edit{margin-top:24px;padding-top:20px;border-top:1px solid #edf1f3}.prof-hours-edit h4{margin:0 0 13px;color:#003070;font-size:.95rem}.hour-row{display:grid;grid-template-columns:minmax(170px,1.5fr) 1fr auto 1fr;gap:10px;align-items:center;padding:9px 11px;margin:5px 0;background:#f8fafb;border:1px solid #edf1f3;border-radius:12px}.hour-row label{font-size:.78rem;font-weight:700;color:#45535d}.hour-row input[type=time]{border:1px solid #d9e2e7;border-radius:9px;background:#fff;padding:8px;color:#34434e;font:inherit}.hour-row span{color:#7b858d;font-size:.76rem;text-align:center}.prof-form-actions{display:flex;gap:10px;margin-top:22px;padding-top:18px;border-top:1px solid #edf1f3}.prof-form-actions .btn-p{border:0;border-radius:12px;padding:11px 18px;background:#1B5E3F;color:#fff;font-weight:800;cursor:pointer;box-shadow:0 6px 14px rgba(27,94,63,.16)}
@media(max-width:720px){#profAdmRoot .prof-adm-head{align-items:stretch;flex-direction:column;padding:20px}.prof-adm-head .btn-p{width:100%;justify-content:center}.prof-adm-card{align-items:flex-start;flex-wrap:wrap;padding:13px}.prof-adm-info{min-width:calc(100% - 84px)}.prof-adm-actions{width:100%;padding-left:84px}.prof-adm-actions button{flex:1}.prof-adm-form{padding:18px 14px;border-radius:18px}.prof-form-grid{grid-template-columns:1fr;gap:13px}.prof-form-grid .full{grid-column:auto}.prof-form-grid .check{padding-top:5px}.hour-row{grid-template-columns:1fr 1fr;gap:8px}.hour-row label{grid-column:1/-1}.hour-row span{display:none}.prof-form-actions{flex-direction:column}.prof-form-actions button{width:100%}}
@media(max-width:400px){.prof-adm-avatar{width:58px;height:58px;min-width:58px}.prof-adm-info{min-width:calc(100% - 72px)}.prof-adm-actions{padding-left:0}.hour-row{grid-template-columns:1fr}.hour-row label{grid-column:auto}}
`;document.head.appendChild(s)}
function inject(){addStyles();if(document.getElementById('profAdmRoot'))return;const host=document.getElementById('tab-config')||document.getElementById('app');if(!host)return;const wrap=document.createElement('div');wrap.id='profAdmRoot';wrap.innerHTML=`<div class="prof-adm-head"><div><span class="tag">Equipa</span><h2>Profissionais</h2><p>Crie e edite os perfis que aparecem no site público.</p></div><button class="btn-p" id="profNovo">+ Novo profissional</button></div><div id="profLista" class="prof-adm-list"></div><div id="profForm" class="prof-adm-form" style="display:none"></div>`;host.appendChild(wrap);load();document.getElementById('profNovo').onclick=()=>form();}
async function load(){const {data,error}=await sb.from('profissionais').select('*').order('ordem').order('nome');const el=document.getElementById('profLista');if(!el)return;if(error){el.innerHTML='<div class="no-data"><p>Erro ao carregar profissionais: '+esc(error.message)+'</p></div>';return;}el.innerHTML=(data||[]).map(p=>`<div class="prof-adm-card"><div class="prof-adm-avatar">${p.foto_url?`<img src="${esc(p.foto_url)}" alt="">`:'<span>👤</span>'}</div><div class="prof-adm-info"><strong>${esc(p.nome)}</strong><span>${esc(p.cargo||p.area_atuacao||'')}</span><small>${p.ativo?'Publicado no site':'Oculto no site'}</small></div><div class="prof-adm-actions"><button onclick='window.editarProfissional(${JSON.stringify(p.id)})'>Editar</button><button class="danger" onclick='window.excluirProfissional(${JSON.stringify(p.id)})'>Excluir</button></div></div>`).join('')||'<div class="no-data"><p>Nenhum profissional cadastrado.</p></div>';}
function form(p={}){const f=document.getElementById('profForm');f.style.display='block';f.innerHTML=`<div class="prof-adm-form-head"><div><span class="tag">Perfil profissional</span><h3>${p.id?'Editar profissional':'Novo profissional'}</h3></div><button type="button" class="ghost-btn" onclick="document.getElementById('profForm').style.display='none'">Fechar</button></div><form id="profissionalForm"><input type="hidden" id="pfId" value="${esc(p.id||'')}"><div class="prof-form-grid"><label>Nome<input id="pfNome" required value="${esc(p.nome||'')}"></label><label>Cargo / função<input id="pfCargo" value="${esc(p.cargo||'')}"></label><label>Área de actuação<input id="pfArea" value="${esc(p.area_atuacao||'')}"></label><label>Ordem<input id="pfOrdem" type="number" value="${Number(p.ordem||0)}"></label><label class="full">Pequena biografia<textarea id="pfBio" rows="3">${esc(p.biografia||'')}</textarea></label><label class="full">O que faz / explicação para o paciente<textarea id="pfDesc" rows="4">${esc(p.descricao||'')}</textarea></label><label>Foto<input id="pfFoto" type="file" accept="image/*"><small>JPG, PNG ou WebP. A foto será guardada no Supabase.</small></label><label class="check"><input id="pfAtivo" type="checkbox" ${p.ativo!==false?'checked':''}> Mostrar este profissional no site</label></div><div class="prof-hours-edit"><h4>Horários livres / atendimento</h4>${DAYS.map(d=>{const x=(p.horarios||[]).find(a=>a.dia===d)||{};return `<div class="hour-row"><label><input class="pf-day" data-day="${d}" type="checkbox" ${x.inicio?'checked':''}> ${d}</label><input class="pf-start" data-day="${d}" type="time" value="${esc(x.inicio||'')}"><span>até</span><input class="pf-end" data-day="${d}" type="time" value="${esc(x.fim||'')}"></div>`;}).join('')}</div><div class="prof-form-actions"><button class="btn-p" type="submit">Guardar profissional</button><button type="button" class="ghost-btn" onclick="document.getElementById('profForm').style.display='none'">Cancelar</button></div></form>`;document.getElementById('profissionalForm').onsubmit=save;f.scrollIntoView({behavior:'smooth',block:'start'});}
async function save(e){e.preventDefault();const id=document.getElementById('pfId').value;let foto=null;const file=document.getElementById('pfFoto').files[0];if(file){const path='profissionais/'+crypto.randomUUID()+'.'+(file.name.split('.').pop()||'jpg');const up=await sb.storage.from('profissionais').upload(path,file,{upsert:false,contentType:file.type});if(up.error){showToast('Erro ao enviar foto: '+up.error.message,'err');return;}foto=sb.storage.from('profissionais').getPublicUrl(path).data.publicUrl;}const horarios=DAYS.map(d=>{const c=document.querySelector(`.pf-day[data-day="${CSS.escape(d)}"]`),a=document.querySelector(`.pf-start[data-day="${CSS.escape(d)}"]`),b=document.querySelector(`.pf-end[data-day="${CSS.escape(d)}"]`);return {dia:d,inicio:a.value,fim:b.value,disponivel:c.checked};}).filter(x=>x.disponivel&&x.inicio&&x.fim);const obj={nome:document.getElementById('pfNome').value.trim(),cargo:document.getElementById('pfCargo').value.trim(),area_atuacao:document.getElementById('pfArea').value.trim(),biografia:document.getElementById('pfBio').value.trim(),descricao:document.getElementById('pfDesc').value.trim(),ordem:Number(document.getElementById('pfOrdem').value||0),ativo:document.getElementById('pfAtivo').checked,horarios};if(foto)obj.foto_url=foto;const {error}=id?await sb.from('profissionais').update(obj).eq('id',id):await sb.from('profissionais').insert(obj);if(error){showToast('Erro ao guardar: '+error.message,'err');return;}showToast('Profissional guardado com sucesso!','ok');document.getElementById('profForm').style.display='none';load();}
window.editarProfissional=async id=>{const {data,error}=await sb.from('profissionais').select('*').eq('id',id).single();if(error)showToast(error.message,'err');else form(data);};
window.excluirProfissional=async id=>{if(!confirm('Excluir este perfil?'))return;const {error}=await sb.from('profissionais').delete().eq('id',id);if(error)showToast('Erro: '+error.message,'err');else{showToast('Profissional removido.','ok');load();}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();
